# Generated by Django 4.2.23 on 2025-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='payment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printorder',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/'),
        ),
        migrations.AddField(
            model_name='printorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A5', 'A5'), ('Letter', 'Letter')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
