# Generated by Django 4.2.23 on 2025-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0003_printorder_payment_note_printorder_payment_slip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=30)),
                ('shaba_number', models.CharField(max_length=34)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
