# Generated by Django 4.2.23 on 2025-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0004_paymentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_approval', 'Awaiting Approval'), ('processing', 'In Progress'), ('ready', 'Ready for Pickup/Delivery'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
