# Generated by Django 4.2.16 on 2025-07-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0005_alter_printorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('binding', 'Binding Options'), ('finishing', 'Finishing Options'), ('packaging', 'Packaging'), ('paper', 'Paper Options')], max_length=50)),
                ('service_type', models.CharField(choices=[('print', 'Print Service'), ('typing', 'Typing Service'), ('both', 'Both Services')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(default='fas fa-tag', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.CharField(choices=[('print', 'Print Service'), ('typing', 'Typing Service'), ('both', 'Both Services')], max_length=20)),
                ('accessories', models.ManyToManyField(to='print_service.accessory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintOrderAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_service.accessory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='print_service.printorder')),
            ],
            options={
                'unique_together': {('order', 'accessory')},
            },
        ),
    ]
