# Generated by Django 4.2.16 on 2025-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0006_accessory_packagedeal_printorderaccessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPriceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price_per_page', models.PositiveIntegerField(default=50000, help_text='Base price per page in Tomans')),
                ('color_price_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Price multiplier for color printing (1.5 = 50% more expensive)', max_digits=3)),
                ('double_sided_discount', models.DecimalField(decimal_places=2, default=0.8, help_text='Discount for double-sided printing (0.8 = 20% discount)', max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Print Pricing Settings',
                'verbose_name_plural': 'Print Pricing Settings',
            },
        ),
    ]
