# Generated by Django 4.2.16 on 2025-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0007_printpricesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='color',
            field=models.CharField(default='#007bff', help_text='رنگ نمایش (کد هگز)', max_length=7),
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر لوازم جانبی', null=True, upload_to='accessories/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='نمایش در بخش ویژه'),
        ),
        migrations.AddField(
            model_name='printpricesettings',
            name='a3_price',
            field=models.PositiveIntegerField(default=100000, help_text='قیمت صفحه A3'),
        ),
        migrations.AddField(
            model_name='printpricesettings',
            name='a4_price',
            field=models.PositiveIntegerField(default=50000, help_text='قیمت صفحه A4'),
        ),
        migrations.AddField(
            model_name='printpricesettings',
            name='a5_price',
            field=models.PositiveIntegerField(default=30000, help_text='قیمت صفحه A5'),
        ),
        migrations.AddField(
            model_name='printpricesettings',
            name='bulk_discount_10',
            field=models.DecimalField(decimal_places=2, default=0.95, help_text='تخفیف برای 10+ صفحه', max_digits=3),
        ),
        migrations.AddField(
            model_name='printpricesettings',
            name='bulk_discount_100',
            field=models.DecimalField(decimal_places=2, default=0.85, help_text='تخفیف برای 100+ صفحه', max_digits=3),
        ),
        migrations.AddField(
            model_name='printpricesettings',
            name='bulk_discount_50',
            field=models.DecimalField(decimal_places=2, default=0.9, help_text='تخفیف برای 50+ صفحه', max_digits=3),
        ),
        migrations.AddField(
            model_name='printpricesettings',
            name='letter_price',
            field=models.PositiveIntegerField(default=45000, help_text='قیمت صفحه Letter'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('binding', 'گزینه\u200cهای صحافی'), ('finishing', 'گزینه\u200cهای تکمیل'), ('packaging', 'بسته\u200cبندی'), ('paper', 'گزینه\u200cهای کاغذ'), ('delivery', 'تحویل'), ('priority', 'اولویت')], max_length=50),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='service_type',
            field=models.CharField(choices=[('print', 'سرویس پرینت'), ('typing', 'سرویس تایپ'), ('both', 'هر دو سرویس')], max_length=20),
        ),
        migrations.AlterField(
            model_name='printpricesettings',
            name='base_price_per_page',
            field=models.PositiveIntegerField(default=50000, help_text='قیمت پایه هر صفحه (تومان)'),
        ),
        migrations.AlterField(
            model_name='printpricesettings',
            name='color_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='ضریب قیمت برای پرینت رنگی (1.5 = 50% گران\u200cتر)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='printpricesettings',
            name='double_sided_discount',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='تخفیف برای پرینت دو رو (0.8 = 20% تخفیف)', max_digits=3),
        ),
    ]
