# Generated by Django 4.2.16 on 2025-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0008_accessory_color_accessory_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsettings',
            options={'verbose_name': 'تنظیمات پرداخت', 'verbose_name_plural': 'تنظیمات پرداخت'},
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صاحب حساب'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='order_validity_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='اعتبار سفارش (ساعت)'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='دستورالعمل پرداخت'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/', verbose_name='QR کد کارت'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='account_number',
            field=models.CharField(max_length=30, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='نام بانک'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='card_number',
            field=models.CharField(max_length=30, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='shaba_number',
            field=models.CharField(max_length=34, verbose_name='شماره شبا'),
        ),
    ]
