# Generated by Django 4.2.23 on 2025-07-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingorder',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='typing_payment_slips/'),
        ),
    ]
