# Generated by Django 4.2.23 on 2025-07-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0002_typingorder_payment_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingorder',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='typing_inputs/'),
        ),
    ]
