# Generated by Django 4.2.23 on 2025-07-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0003_typingorder_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingorder',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
