# Generated by Django 4.2.23 on 2025-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0004_typingorder_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingorder',
            name='final_approved',
            field=models.BooleanField(default=False),
        ),
    ]
