# Generated by Django 4.2.23 on 2025-07-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0005_typingorder_final_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingorder',
            name='final_approved_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
