# Generated by Django 4.2.23 on 2025-07-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0006_typingorder_final_approved_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingorder',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('email', 'ایمیل'), ('print', 'نسخه چاپی')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('accepted', 'در حال انجام'), ('rejected', 'رد شده'), ('done', 'انجام شده')], default='pending', max_length=20),
        ),
    ]
