# Generated by Django 4.2.23 on 2025-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0007_typingorder_delivery_option_alter_typingorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingorder',
            name='final_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
