# Generated by Django 4.2.23 on 2025-07-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0008_typingorder_final_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingorder',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('print', 'Printed by staff'), ('email', 'Sent to email')], max_length=10, null=True, verbose_name='Delivery Option'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='typing_documents/', verbose_name='Document to Type'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Delivery'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='final_approved',
            field=models.BooleanField(default=False, verbose_name='Admin Final Approval'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='final_approved_by_user',
            field=models.BooleanField(default=False, verbose_name='User Final Approval'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='final_note',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Final Note'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='page_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Page Count'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='typing_payment_slips/', verbose_name='Payment Slip'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_approval', 'Awaiting Approval'), ('in_progress', 'In Progress'), ('awaiting_final_approval', 'Awaiting Final Approval'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_review', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0, help_text='Set by admin after review.', verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='typingorder',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User Phone'),
        ),
    ]
