# Generated by Django 4.2.23 on 2025-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0009_alter_typingorder_delivery_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingPriceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_page', models.PositiveIntegerField(default=1000, help_text='The default price per page for a standard typing order.', verbose_name='Price per Page')),
            ],
            options={
                'verbose_name': 'Typing Pricing Settings',
                'verbose_name_plural': 'Typing Pricing Settings',
            },
        ),
    ]
