# Generated by Django 4.2.16 on 2025-07-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0006_accessory_packagedeal_printorderaccessory'),
        ('typing_service', '0010_typingpricesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingOrderAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_service.accessory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='typing_service.typingorder')),
            ],
            options={
                'unique_together': {('order', 'accessory')},
            },
        ),
    ]
