# Generated by Django 4.2.16 on 2025-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_service', '0011_typingorderaccessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingpricesettings',
            name='bulk_discount_10',
            field=models.DecimalField(decimal_places=2, default=0.9, help_text='تخفیف برای 10+ صفحه', max_digits=3),
        ),
        migrations.AddField(
            model_name='typingpricesettings',
            name='bulk_discount_20',
            field=models.DecimalField(decimal_places=2, default=0.85, help_text='تخفیف برای 20+ صفحه', max_digits=3),
        ),
        migrations.AddField(
            model_name='typingpricesettings',
            name='bulk_discount_5',
            field=models.DecimalField(decimal_places=2, default=0.95, help_text='تخفیف برای 5+ صفحه', max_digits=3),
        ),
        migrations.AddField(
            model_name='typingpricesettings',
            name='email_delivery_price',
            field=models.PositiveIntegerField(default=0, help_text='هزینه تحویل از طریق ایمیل'),
        ),
        migrations.AddField(
            model_name='typingpricesettings',
            name='print_delivery_price',
            field=models.PositiveIntegerField(default=50000, help_text='هزینه تحویل چاپی'),
        ),
        migrations.AddField(
            model_name='typingpricesettings',
            name='urgent_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='ضریب قیمت برای تایپ فوری (1.5 = 50% گران\u200cتر)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='typingpricesettings',
            name='price_per_page',
            field=models.PositiveIntegerField(default=100000, help_text='قیمت پایه هر صفحه (تومان)', verbose_name='Price per Page'),
        ),
    ]
