# Generated by Django 4.2.16 on 2025-08-03 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='payment_receipts/', verbose_name='تصویر رسید')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تراکنش')),
                ('depositor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام واریزکننده')),
                ('deposit_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ واریز')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ واریز شده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='digital_shop.order')),
            ],
            options={
                'verbose_name': 'رسید پرداخت',
                'verbose_name_plural': 'رسیدهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
